# Generated by Django 5.1.3 on 2025-02-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverbQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='adverb_images/')),
                ('correct_adverb', models.CharField(max_length=100)),
                ('options', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
