# Generated by Django 5.1.3 on 2025-02-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_adverbquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='meaning',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
